DEVICE_ID: 0
MODEL:
  NAME: MLP
  NUM_BLOCKS: 1
  NUM_HIDDEN_LAYERS: 2
  NUM_HIDDEN_NEURONS: 1024
NUM_EXPERIMENT_REPETITIONS: 1
ROBOT_CHOICE: All-DoF
SEED_CHOICE: true
SEED_NUMBER: 1
TRAIN:
  CHECKPOINT:
    LOAD_OPTIONS: local
    PRETRAINED_G_MODEL: ''
    RESUMED_G_MODEL: ''
    SAVE_OPTIONS: local
  DATASET:
    JOINT_LIMIT_SCALE: 10
    JOINT_VARIATION: 1
    NUM_SAMPLES: 1000000
    ORIENTATION: RPY
    TYPE: combine-up-to-7DoF
  HYPERPARAMETERS:
    BATCH_SIZE: 128
    BETAS:
    - 0.9
    - 0.999
    EPOCHS: 2
    EPS: 1.0e-05
    LEARNING_RATE: 0.001
    LOSS: lq
    NUM_WORKERS: 4
    OPTIMIZER_NAME: Adam
    PERSISTENT_WORKERS: true
    PIN_MEMORY: false
    SHUFFLE: true
    WEIGHT_DECAY: 0.0
    WEIGHT_INITIALIZATION: default
  PRINT_EPOCHS: true
  PRINT_STEPS: 100
